apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.admin.user }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.admin.password }}
