apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: monitoring
data:
  telegraf.conf: |
    [[inputs.snmp]]
      agents = ["192.168.49.1:161"]
      version = 2
      community = "public"

      [[inputs.snmp.field]]
        name = "sysDescr"
        oid = ".1.3.6.1.2.1.1.1.0"
        is_tag = true

      [[inputs.snmp.field]]
        name = "sysName"
        oid = ".1.3.6.1.2.1.1.5.0"
        is_tag = true

      [[inputs.snmp.field]]
        name = "sysUpTime"
        oid = ".1.3.6.1.2.1.1.3.0"

      [[inputs.snmp.field]]
        name = "ifInOctets_1"
        oid = ".1.3.6.1.2.1.2.2.1.10.1"

      [[inputs.snmp.field]]
        name = "ifOutOctets_1"
        oid = ".1.3.6.1.2.1.2.2.1.16.1"

    [[outputs.prometheus_client]]
      listen = ":9273"


# [[inputs.snmp]]
#   agents = ["192.168.49.1:161"] # IP de Minikube
#   version = 2
#   community = "public"
#   [[inputs.snmp.field]]
#     name = "sysDescr"
#     oid = ".1.3.6.1.2.1.1.1.0"

# [[outputs.prometheus_client]]
#   listen = ":9273"


# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: telegraf-config
#   namespace: monitoring
# data:
#   telegraf.conf: |
#     [[inputs.snmp]]
#       agents = ["<IP_del_dispositivo_SNMP>:161"]
#       version = 2
#       community = "public"
#       [[inputs.snmp.field]]
#         name = "sysDescr"
#         oid = ".1.3.6.1.2.1.1.1.0"

#     [[inputs.mqtt_consumer]]
#       servers = ["tcp://<IP_del_servidor_MQTT>:1883"]
#       topics = ["#"]
#       client_id = "telegraf-mqtt-client"
#       qos = 0

#     [[outputs.prometheus_client]]
#       listen = ":9273"
