apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:latest
        volumeMounts:
        - name: config-volume
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
        ports:
        - containerPort: 9273
      volumes:
      - name: config-volume
        configMap:
          name: telegraf-config
