apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9273
      nodePort: 30000  # Elige un puerto disponible entre 30000 y 32767
  selector:
    app: telegraf  # Asegúrate de que esto coincida con las etiquetas de tu pod de Telegraf